#Exception block we are using
'''
1-try :just used to set the block of code
2-except : help us to handle the errors
3-finally :block will get executed at all cases
'''


'''
try :
    x=1/0
except:
    print("Wrong division")
finally:
    print("Always being executed")
'''

'''
try :
    for i in range(1,20):
        if(i==5):
            x=i/0
        else:
           print(i)
except:
    print("Division  by 0 is not possible")
finally:
    print("End of try and except method")
'''   
